# site settings
title: Bahar Afshari
subtitle: My Projects
email: afsharizand@gmail.com
description: A brief history of my projects
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Daneshjoo Blv.
city: Tehran
state: Tehran
zip_code: 1981973883
country: Iran
phone: 0911-114-0399

# homepage tiles
tiles-source: Projects # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/baharAfshari
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/bahar-afshari/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
